name: Sync

on: 
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron:  '* */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get-docker
        uses: actions/setup-python@v2
    
      - name: cache-files
        uses: actions/checkout@v2

      - name: run
        env:
          GITEE_ACCESS_TOKEN: ${{ secrets.GITEE_ACCESS_TOKEN }}
          NODES: ${{ secrets.NODES }}
        run: 
          pip3 install requests && python3 run.py
          
