name: Sync

on: 
  push:
    branches:
      - main
  workflow_dispatch:
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout master
        uses: actions/checkout@v2
          
      - name: test
        env: # 设置环境变量
          PRIV_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}# toKen私密变量
        run: 
          bash ./sync.sh 
          
