name: Sync

on: 
  push:
    branches:
      - main
  workflow_dispatch:
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
      steps:
        run:
          echo "hello"
