name: Sync

on: 
  push:
    branches:
      - main
  workflow_dispatch:
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout master
        uses: actions/checkout@v2
          
      - name: update_gitee_apis_nodes
        use: python3.8-alpine
        env:
          PRIV_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}# toKen私密变量
        run: 
          pip3 install requests && python3 test.py
          
